spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: test  # 激活测试环境配置
  ai:
    openai:
      api-key: sk-0c7bd94e3aa540a089b68a8ffad23593
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat


